### ISSUE TITLE
AppBar app discards keyboard backlight setting

### ISSUE THREAD

**Issue by kani7** [shymega/planet-devices#65] opened 2023-03-02 16:07 UTC
When Planet AppBar app is enabled, Cosmo's keyboard backlight setting is discarded after OS reboot.

**Comment by ZimbiX** [comment] 2023-03-02 20:57
Duplicate of https://github.com/shymega/planet-devices/issues/13 - please close. Sounds like you found the cause though! :clap:

**Closed** 2023-03-02 20:58 UTC
Labels: Cosmo-Communicator
