### ISSUE TITLE
ASTRO Slide 5G Astro-11.0-Planet-05242023-V07b Fingerprint good for Login but not working with apps

### ISSUE THREAD

**Issue by SScheiper** [shymega/planet-devices#83] opened 2024-11-29 15:44 UTC
Hello!

After resetting my Astro i can't get the fingerprint to work with any App, Login works fine, Apps report that at least one fingerprint needs to be stored. Resetting all this did not solve the problem, checking over ADB with tools showed the rights being correctly set, some setting seems to wrong in Android or maybe some security stuff that prevents the apps from accepting the Biometrics or Android not using it,
Anybody who has an idea what that could be and how to solve or maybe somebody who had the problem as well and found something?

Thanks!
-Stefan

**Comment by ZimbiX** [comment] 2024-11-29 17:36
Duplicate of https://github.com/planet-community/planet-devices/issues/43

**Comment by shymega** [comment] 2024-12-01 21:18
Closing as dupe - note to all, please do check the issue tracker before opening issues :-) Thanks!

**Closed as not planned** 2024-12-01 21:18 UTC
Labels: duplicate, Astro-Slide, Android-FW
