### ISSUE TITLE
System Update notification is persistent forever.

### ISSUE THREAD

**Issue by Dinoraptor101** [shymega/planet-devices#81] opened 2023-11-07 12:39 UTC
This issue first observed after second reboot. is reproduced on reboot.
System Update notification appears and persists forever but there is nothing to update

play store apps up to date
planet computer update is up to date
tapping notifications does nothing. notification cannot dismiss.

detected on 
Astro Slide 5g
Android 11
Build Number: Astro-11.0-Planet-05242023-V07b

**Comment by Dinoraptor101** [comment] 2023-11-07 12:53
found separate option "System update" in settings.  manually clicking it seems to dismiss the notifications.

will keep the issue open thou since notifications are not going away on their own (the check does not complete)

**Comment by ZimbiX** [comment] 2023-11-07 13:28
Duplicate of https://github.com/shymega/planet-devices/issues/45. Although after I eventually updated to v07b, I don't have this issue myself anymore.

**Closed as not planned by ZimbiX** 2023-11-07 13:28 UTC
Labels: Astro-Slide, Android-FW
