### ISSUE TITLE
 Cannot take screenshot properly with portrait orientation.

### ISSUE THREAD

**Issue by kani7** [shymega/planet-devices#61] opened 2023-03-02 15:23 UTC
With portrait orientation, Cosmo's built-in screenshot function works with wrong aspects ratio and size.

**Comment by ZimbiX** [comment] 2023-03-02 20:47
Duplicate of https://github.com/shymega/planet-devices/issues/34 - please close

**Closed** 2023-03-02 20:58 UTC
Labels: Cosmo-Communicator
