### ISSUE TITLE
Astro Slide: Screen momentarily going white at full brightness when going to sleep

### ISSUE THREAD

**Issue by ThePhilStrongProject** [shymega/planet-devices#4] opened 2022-12-08 10:03 UTC
Astro flashes a white full brightness screen momentarily when going to sleep (the device, not me), if the brightness has been set super low. This is awkward as the only time I set the brightness that low is when going to bed - and just as I'm putting the phone down I get flashbanged by my Astro which is quite uncomfortable!

**Comment by Daz-Mataz** [comment] 2023-01-07 08:36
For me awaking the device with a press of the power button brings on a full screen  brightness regardless of setting, for around 3 second before the actual setting level is applied.

**Comment by Daz-Mataz** [comment] 2023-01-08 03:33
> I'm finding this is due to the Automatic Brightness setting - disabling that stops the issue for me.

This does not fix the issue for me. When I set the brightness to 1% the screen acts as previously stated, when the brightness is set to 18%, which to my eyesight is the first noticeable jump in brightness from 1%, the screen flash bangs at 100% brightness and then returns to 18% very quickly. This is the same for 24% and all the way up to 85%. At 85% there doesn't appear to be a lag in returning to the set brightness, however the difference between 85% and 100% brightness is less noticeable in general, but i get a feeling it still happens just very very quickly. At 18% brightness and above there are times when the flash bang effect doesn't occur but this is around a one in five chance.

**Comment by shymega** [comment] 2023-01-08 15:52
Hm, it fixes it for me. Hasn't happened since I disabled it. I am on an older dev firmware though.

**Comment by ThePhilStrongProject** [comment] 2023-01-08 20:28
Nope, definitely still happens with auto brightness off.

**Comment by olmari** [comment] 2023-01-08 20:42
I can confirm this happens on my Astro too with auto brightness off. It's not long duration, but brief high intensity "flash" is not fun at dark.

**Comment by shymega** [comment] 2023-01-08 23:15
I also turned off 'Lift to Wake', but I can't help but think it's a regression in newer, non-developer firmwares.

**Comment by Daz-Mataz** [comment] 2023-01-09 14:17
> I also turned off 'Lift to Wake', but I can't help but think it's a regression in newer, non-developer firmwares.

Just to follow up, Lift to wake switched off doesn't fix the issue.

**Comment by shymega** [comment] 2023-03-27 17:06
I can confirm that this has been fixed in the next firmware release. No timeframe for the publication of the next firmware, but it brings many bug fixes, and a new security patch level. Not closing yet, until users confirm the fix works - when the update is released.

**Comment by ZimbiX** [comment] 2023-05-25 10:47
This appears to be fixed in the V07 firmware =)

**Closed by ZimbiX** 2023-05-25 10:47 UTC
Labels: Astro-Slide, Android-FW
